vich_uploader:
    db_driver: orm

    mappings:
        banner_image:
            uri_prefix: '%app.path.banner_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.banner_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        post_image:
            uri_prefix: '%app.path.post_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
